version: '3.8'

services:

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    environment:
      - DOMAIN=gateway
      - PORT=80
    depends_on:
      - mysql
      - gateway
    networks:
      - app-network
  
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf"
      - "./nginx/mime.types:/etc/nginx/mime.types"
      - "./nginx/sites:/etc/nginx/conf.d/"
    depends_on:
      - mysql
    networks:
      - app-network
  
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=FGHqB0nR
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  mangement-app:
    build:
      context: ../management-app
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ../management-app:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  kitchen-app:
      build:
        context: ../kitchen-app
        dockerfile: ./docker/php-fpm/Dockerfile
      restart: on-failure
      working_dir: /var/www
      volumes:
        - ../kitchen-app:/var/www
      depends_on:
        - mysql
      networks:
        - app-network

  inventory-app:
    build:
      context: ../inventory-app
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ../inventory-app:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge

  